// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Words_from_Strangers.Models;

#nullable disable

namespace Words_from_Strangers.Migrations
{
    [DbContext(typeof(MessageContext))]
    partial class MessageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Words_from_Strangers.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"), 1L, 1);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            DateAdded = new DateTime(2025, 11, 28, 21, 33, 49, 969, DateTimeKind.Local).AddTicks(5181),
                            Location = "Earth",
                            MessageText = "Hello World",
                            Name = "BDAhearn"
                        },
                        new
                        {
                            MessageId = 2,
                            DateAdded = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Antartica",
                            MessageText = "What's up everyone"
                        },
                        new
                        {
                            MessageId = 3,
                            DateAdded = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MessageText = "Hi, I'm Dave.",
                            Name = "Dave"
                        },
                        new
                        {
                            MessageId = 4,
                            DateAdded = new DateTime(2020, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "France",
                            MessageText = "Honhonhon qui qui"
                        },
                        new
                        {
                            MessageId = 5,
                            DateAdded = new DateTime(2222, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mars",
                            MessageText = "Why am I on mars?",
                            Name = "Bek"
                        },
                        new
                        {
                            MessageId = 6,
                            DateAdded = new DateTime(2023, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lordran",
                            MessageText = "I can't wait to start this bonfire"
                        },
                        new
                        {
                            MessageId = 7,
                            DateAdded = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "New Londo",
                            MessageText = "I have not seen the sun for a long time. Perhaps I could do with a change... "
                        },
                        new
                        {
                            MessageId = 8,
                            DateAdded = new DateTime(2012, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MessageText = "Hey guys, I think Im lost"
                        },
                        new
                        {
                            MessageId = 9,
                            DateAdded = new DateTime(2019, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Universe B",
                            MessageText = "It's great an Earth day is 25 hours long",
                            Name = "Asher"
                        },
                        new
                        {
                            MessageId = 10,
                            DateAdded = new DateTime(2000, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MessageText = "Who am I? Where am I?"
                        },
                        new
                        {
                            MessageId = 11,
                            DateAdded = new DateTime(2011, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MessageText = "All your base are belong to us",
                            Name = "Aila"
                        },
                        new
                        {
                            MessageId = 12,
                            DateAdded = new DateTime(2014, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MessageText = "Have you really been far even as decided to use even go want to do look more like?",
                            Name = "Claire"
                        },
                        new
                        {
                            MessageId = 13,
                            DateAdded = new DateTime(2018, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Canada",
                            MessageText = "Where did the geese go"
                        },
                        new
                        {
                            MessageId = 14,
                            DateAdded = new DateTime(2009, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mirror Earth",
                            MessageText = "The moon is really cool",
                            Name = "Yue"
                        },
                        new
                        {
                            MessageId = 15,
                            DateAdded = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Slightly Better Florida",
                            MessageText = "Freedom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
